name: xec
favicon: null
layout_spectrum: 0.8873921150807291
typography_spectrum: 0.7242791226599365
title: Anatal Electronics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03030d'
    - '#0062b3'
    - '#58b8eb'
    - '#00275b'
    - '#92e8d9'
  brandStrength: 0.8986141481436789
  lightness: 0.053655875846743584
  saturation: 0.75
  rhythmicContrast: 0.9824706567451358
purpose: []
